#hexo new page 
menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    书籍: /book/ || fas fa-book
  关于: /about/ || fas fa-heart

#hexo description
index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config

#banner
index_img: https://s2.loli.net/2022/03/07/hdjq5KaxNSH4cnI.jpg

